### PR TITLE
Show value of the constant on the node's output in editor

### PR DESCRIPTION
**Pull request by gildorwang**
It's hard to understand the graph when there are many Constants... Showing their values makes it a bit easier.

image

### CODE REVIEW

**Comment by dy-sh** [comment]
What if the value is too large or odd? 
I'm working on the node.js port of this project and I've already implemented the same option there. 
I used simple rules for creating a readable string. https://github.com/derwish-pro/singlehub/blob/master/public/nodes/utils.js#L226

**Comment by gildorwang** [comment]
The node expands itself, but a little truncating/formatting is even better! 
I can make similar changes here if you don't mind.

**Comment by gildorwang** [comment]
By the way, what's the plan on these projects? I'm looking to make more improvements on the .NET version. Knowing some details/gaps between them might help keep things consistent. 😃

**Comment by dy-sh** [comment]
At the moment, the version on .net has not received much support from other developers. I think this is due to the unpopularity of .net in the audience for which the project is designed. For this reason, I decided to rewrite it to the node. I thought that I would support both projects at the same time, at least for the first time. But when I started writing the project on the node, I decided to do some things differently, using the experience I had already gained. Now the new project is ready for 70%. But it already has cool options that are not yet implemented in this project, and now I'm not so sure that I'll find the time to make them here (step by step nodes execution,
display values ​​for nodes inputs/outputs in real time, MQTT protocol support, etc...). https://github.com/derwish-pro/singlehub/blob/master/CHANGELOG.md

**Comment by gildorwang** [comment]
@derwish-pro Sounds good. I checked out the new project. I like the idea but as you said it's not really ready yet, so I'll continue use this project for now because I already have my home sensor network built up. And I'll be happy to port some features here if I got the time. (Got some life-changing events recently - sorry for the late reply)

**Comment by dy-sh** [comment]
Thank you for participating.

**Pull request merged**
